# Generated by Django 5.2.6 on 2025-10-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_powder_productionorder_qcreport_utilitydata'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='utilitydata',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='electricity_used',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='gas_used',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='water_used',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='utilitydata',
            name='powder_consumption',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='utilitydata',
            name='powder_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='utilitydata',
            name='electricity_usage',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='utilitydata',
            name='gas_consumption',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='utilitydata',
            name='water_usage',
            field=models.FloatField(default=0),
        ),
    ]
