# Generated by Django 5.2.6 on 2025-10-13 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_utilitydata_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='utilitydata',
            unique_together={('date',)},
        ),
    ]
