# Generated by Django 5.2.6 on 2025-10-13 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_utilitydata_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtilityConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gas_consumption', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('electricity_usage', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='electricity_used',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='gas_used',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='production_line',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='water_used',
        ),
        migrations.RemoveField(
            model_name='qcreport',
            name='inspector',
        ),
        migrations.RemoveField(
            model_name='qcreport',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='qcreport',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='qcreport',
            name='report_id',
        ),
        migrations.RemoveField(
            model_name='qcreport',
            name='result',
        ),
        migrations.RemoveField(
            model_name='qcreport',
            name='test_date',
        ),
        migrations.AddField(
            model_name='productionorder',
            name='order_number',
            field=models.CharField(default='TEMP_ORDER', max_length=50),
        ),
        migrations.AddField(
            model_name='qcreport',
            name='failed_tests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qcreport',
            name='pass_rate',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='qcreport',
            name='passed_tests',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='qcreport',
            name='production_order',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='dashboard.productionorder'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='product_name',
            field=models.CharField(default='TEMP_PRODUCT', max_length=100),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='status',
            field=models.CharField(default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('operator', 'Operator'), ('viewer', 'Viewer')], default='viewer', max_length=20),
        ),
    ]
