# Generated by Django 5.2.6 on 2025-10-14 04:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_utilityconsumption_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='qcreport',
            name='inspector',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qcreport',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='qcreport',
            name='product_name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qcreport',
            name='report_id',
            field=models.CharField(default=0, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qcreport',
            name='result',
            field=models.CharField(choices=[('passed', 'Passed'), ('failed', 'Failed'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='qcreport',
            name='test_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
