# Generated by Django 5.2.6 on 2025-10-14 04:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_qcreport_inspector_qcreport_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionorder',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='due_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='electricity_used',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='gas_used',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='order_id',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='production_line',
            field=models.CharField(default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='productionorder',
            name='water_used',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='productionorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='inspector',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='product_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='production_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.productionorder'),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='report_id',
            field=models.CharField(default='', max_length=50, unique=True),
        ),
    ]
