# Generated by Django 6.0.1 on 2026-02-14 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_productionorder_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='powder',
            name='price_per_kg',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
