# Generated by Django 6.0.1 on 2026-04-07 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_powder_price_per_kg'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GasRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(default='Argon', max_length=50)),
                ('capacity', models.FloatField(default=0)),
                ('current_level', models.FloatField(default=0)),
                ('refill_date', models.DateField(blank=True, null=True)),
                ('cost', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('todo', 'To Do'), ('in_progress', 'In Progress'), ('review', 'Review'), ('done', 'Done')], default='todo', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('assignee', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ProductionLog',
        ),
        migrations.RemoveField(
            model_name='productionorder',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='qcreport',
            name='production_order',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UtilityConsumption',
        ),
        migrations.DeleteModel(
            name='UtilityData',
        ),
        migrations.AlterModelOptions(
            name='qcreport',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='qcreport',
            old_name='test_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='qcreport',
            old_name='product_name',
            new_name='powder_type',
        ),
        migrations.RemoveField(
            model_name='qcreport',
            name='failed_tests',
        ),
        migrations.RemoveField(
            model_name='qcreport',
            name='pass_rate',
        ),
        migrations.RemoveField(
            model_name='qcreport',
            name='passed_tests',
        ),
        migrations.RemoveField(
            model_name='qcreport',
            name='report_id',
        ),
        migrations.AddField(
            model_name='powder',
            name='color',
            field=models.CharField(default='#E8771A', max_length=20),
        ),
        migrations.AddField(
            model_name='powder',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='qcreport',
            name='adhesion',
            field=models.CharField(blank=True, default='5B', max_length=20),
        ),
        migrations.AddField(
            model_name='qcreport',
            name='batch_id',
            field=models.CharField(default='DEFAULT_BATCH', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='qcreport',
            name='thickness',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='qcreport',
            name='visual',
            field=models.CharField(blank=True, default='OK', max_length=50),
        ),
        migrations.AlterField(
            model_name='powder',
            name='current_stock',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='powder',
            name='min_level',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='qcreport',
            name='result',
            field=models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail')], default='Pass', max_length=10),
        ),
        migrations.DeleteModel(
            name='ProductionOrder',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
